swagger: "2.0"
info:
  title: Password Management Services API
  description: API for password management services
  version: 1.0.0
host: apigrid.opentext.com
basePath: /PasswordManagementServices/v1
schemes:
  - https
paths:
  /accounts/credentials:
    post:
      summary: Initiate password reset request
      description: Initiate password reset request
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: passwordResetRequestInfo
          description: Password reset request information
          schema:
            $ref: '#/definitions/PasswordResetRequestInfo'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/PasswordResetResponse'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
  /accounts/credentials/{id}:
    get:
      summary: Get password reset request details by ID
      description: Get password reset request details by ID
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: Password reset request ID
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/PasswordResetRequest'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  PasswordResetRequestInfo:
    type: object
    properties:
      accountEmail:
        type: string
        description: Email ID associated with the account
      accountId:
        type: string
        description: Account ID
      serviceCode:
